### ISSUE TITLE
Request- Higher Ping Count

### ISSUE THREAD

**Issue by macjeff** [markv58/UDI-Ping#1]
I have a device for Orbit Irrigation that connects to a server on their end.  For some reason when there server is down for a few min my side goes offline but then comes back on its own.  Problem is its enough to set the OFF NETWORK status which quickly changes back.

So I want to go for a longer time.  I went to set Missed Ping >10 or something like that but you cant go past 5.

Is there a way you could leave everything the same but allow the missed ping counter to go up until it reaches a connection and then reset to 0.   You could cap it at something like 100 so you dont have to handle a huge number if down for a long time.  

Thanks!!!

**Comment by markv58** [comment]
Increased missed ping count to max 1440
